apiVersion: v1
kind: ConfigMap
metadata:
  name: cavalry-config
  namespace: vadym-cavalry
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_RABBITMQ_HOST: "rabbitmq"
---
apiVersion: v1
kind: Secret
metadata:
  name: cavalry-secret
  namespace: vadym-cavalry
type: Opaque
stringData:
  POSTGRES_DB: ev_charge_db
  POSTGRES_USER: root
  POSTGRES_PASSWORD: rootpassword
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin