apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: cavalry-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: cavalry-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cavalry-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: cavalry-project
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak