apiVersion: v1
kind: Secret
metadata:
  name: cavalry-secret
  namespace: cavalry-project
type: Opaque
data:
  POSTGRES_DB: ZXZfY2hhcmdlX2Ri
  POSTGRES_USER: cm9vdA==
  POSTGRES_PASSWORD: cm9vdHBhc3N3b3Jk
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=